# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: frontpage.heading
description: Data Platform Prototype
url: ""
data_dir: data
environment: staging
remote_data_prefix: "https://DnsTestEnvironment.github.io/dns-data"
# URL for the "Edit Data" button on indicators.
data_edit_url: http://prose.io/#DnsTestEnvironment/dns-data/edit/develop/data/indicator_[id].csv
# URL for the "Edit Metadata" button on indicators.
metadata_edit_url: http://prose.io/#DnsTestEnvironment/dns-data/edit/develop/meta/[id].md
# permalink: /news/:year/:month/:day/:title.html

# Automatically create indicator pages, goal pages,
# and some other required pages.
create_indicators:
  layout: indicator
create_goals:
  layout: goal-by-target
  previous_next_links: false

create_pages: true

frontpage_goals_grid:
    title: frontpage.heading
    description: frontpage.instructions


analytics:
  ga_prod: ''

###################################################################################################
email_contacts:
  questions: dns-indikatoren@destatis.de
  suggestions: dns-indikatoren@destatis.de
  functional: dns-indikatoren@destatis.de
###################################################################################################


# Build settings
markdown: kramdown

exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE


# International Support
# Eg name: Australia and adjective: Australian.
country:
  name: Germany
  adjective: German

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# The list of languages that are translated. The first one is the default.
languages:
  - de
  - en

logos:
  - src: assets/img/de/DNS_logo.png
    alt: DESTATIS - Deutsche Nachhaltikeitsstrategie
  - language: en
    src: assets/img/en/DNS_logo.png
    alt: DESTATIS - German Strategy for Sustainable Development

date_formats:
  - type: standard
    language: de
    format: "%d.%m.%Y"
  - type: standard
    language: en
    format: "%b %d, %Y"


# Menu
menu:
  - path: /
    translation_key: general.seventeen_goals
  - translation_key: menu.status_title
    dropdown:
      - path: /status_summary/
        translation_key: menu.status_summary
      - path: /status/
        translation_key: menu.status
  - translation_key: menu.about
    dropdown:
      - path: /about_platform/
        translation_key: menu.about_this_site
      - path: /about_joint_action/
        translation_key: menu.community
      - path: /about_guidance/
        translation_key: menu.guidance
  - translation_key: menu.publications
    dropdown:
      - path: /publications_reports/
        translation_key: menu.reports
      - path: /publications_strategy/
        translation_key: menu.sustainable_development_strategy
      - path: /publications_other/
        translation_key: menu.other_publications
  - path: menu.pathtosdg
    translation_key: menu.sdglogo

frontpage_cards:
    - rule_color: grey
      title: ''
      include: components/download-all-data.html
    - rule_color: grey
      title: ''
      include: components/community.html
    - rule_color: grey
      title: ''
      include: components/government.html



contrast_type: single

header_language_toggle: links
header:
    include: header-default.html

footer_menu:
  - path: 'mailto:dns-indikatoren@destatis.de' #menu.contactPath
    translation_key: menu.contact_us
  - path: menu.twitterPath #https://twitter.com/destatis?lang=de
    translation_key:  general.twitter
    alert: twitter
  - path: /imprint/
    translation_key: menu.imprint

metadata_tabs:
  - scope: national
    title: indicator.details
    description: indicator.dns_metadata_blurb
  - scope: content
    title: indicator.contentAndProgress
    description: ''
  - scope: history_1
    title: indicator.history
    description: indicator.history_blurb
  - scope: sources
    title: indicator.sources
    description: ''
# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: indicator.national_metadata

search_index_extra_fields:
  #- indicator_number
  - national_indicator_available
  - indicator_name
  - target_name
  - target_id
  - data_keywords
  - graph_title

footer_fields:
  - unit: '%'
    label: metadata_fields.computation_units
    value: data.%
  - unit: number
    label: metadata_fields.computation_units
    value: data.number


series_toggle: true
graph_title_from_series: false
decimal_separator: ','
thousands_separator: ' '
#graph_color_headline: '#b8b8b8' #
graph_color_headline: ['#e5243b', '#dda63a', '#4c9f38', '#c5192d', '#ff3a21', '#26bde2', '#fcc30b', '#a21942', '#fd6925', '#dd1367', '#fd9d24', '#bf8b2e', '#3f7e44', '#0a97d9', '#56c02b', '#00689d', '#19486a']
useHeadlineColor: false
no_value_character: ' '


hide_empty_metadata: true
hide_single_unit: true

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins


# Use a remote Jekyll theme.
#remote_theme: brockfanning/open-sdg@alter-data-display-decimal-fix
remote_theme: open-sdg/open-sdg@2.2.0

goal_image_base: https://g205sdgs.github.io/sdg-indicators/assets/img/goals/dns

accessible_tabs: true
accessible_charts: true

custom_js:
  - /assets/js/custom.js

graph_color_set: 'goal'
graph_color_number: 9

disclaimer:
  phase: beta

# Mapping
map_options:
  disaggregation_controls: true

  # Control the limits on zooming in/out in the map:
  minZoom: 0
  maxZoom: 11
  # If you would like to use tile (background) imagery, use these:
  tileURL: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
  tileOptions:
    id: mapbox.light
    accessToken: pk.eyJ1IjoibW9ib3NzZSIsImEiOiJjazU1M2trazQwYnFwM2trYmdwNm9rOWxkIn0.u36w-RJPqoTGmivl_zED1w
    attribution: <a href="https://www.openstreetmap.org/copyright">&copy; OpenStreetMap</a> contributors |<br class="visible-xs"> <a href="https://www.bkg.bund.de">&copy; GeoBasis-De / BKG 2023</a> |<br class="hidden-lg"> <a href="https://www.destatis.de/DE/Home/_inhalt.html">&copy; Statistisches Bundesamt (Destatis), 2023</a>
  # Control the choropleth color range. See https://gka.github.io/chroma.js/#chroma-brewer
  # 1 map color depending on goal --- start ---
  #colorRange: ["#F6E8EC", "#E3BAC6", "#D18CA1", "#BE5E7B", "#AB3055", "#A21942", "#821435", "#610F28", "#410A1A", "#20050D"]
  colorRange: [["#FCE9EB", "#F7BDC4", "#F2929D", "#ED6676", "#E83A4F", "#E5243B", "#B71D2F", "#891623", "#5C0E18", "#2E070C"],
              ["#FCF8EB", "#F7E9C2", "#F2DB9A", "#EDCD72", "#E8BE49", "#E5B735", "#CEA530", "#A08025", "#735C1B", "#453710"],
              ["#EDF5EB", "#C9E2C3", "#A6CF9C", "#82BC74", "#5EA94C", "#4C9F38", "#3D7F2D", "#2E5F22", "#1E4016", "#0F200B"],
              ["#F9E8EA", "#EEBAC0", "#E28C96", "#D65E6C", "#CB3042", "#C5192D", "#9E1424", "#760F1B", "#4F0A12", "#270509"],
              ["#FFEBE9", "#FFC4BC", "#FF9D90", "#FF7564", "#FF4E37", "#FF3A21", "#CC2E1A", "#992314", "#66170D", "#330C07"],
              ["#E9F8FB", "#BEEBF6", "#93DEF0", "#67D1EA", "#3CC4E5", "#26BDE2", "#1E97B5", "#177188", "#0F4C5A", "#08262D"],
              ["#FFF9E7", "#FEEDB6", "#FEE185", "#FDD554", "#FCC923", "#FCC30B", "#CA9C09", "#977507", "#654E04", "#322702"],
              ["#F6E8EC", "#E3BAC6", "#D18CA1", "#BE5E7B", "#AB3055", "#A21942", "#821435", "#610F28", "#410A1A", "#20050D"],
              ["#FFF0E9", "#FED2BE", "#FEB492", "#FE9666", "#FD783B", "#FD6925", "#CA541E", "#983F16", "#652A0F", "#331507"],
              ["#FCE7F0", "#F5B8D1", "#EE89B3", "#E75A95", "#E02B76", "#DD1367", "#B10F52", "#850B3E", "#580829", "#2C0415"],
              ["#FFF5E6", "#FEE2B3", "#FECE80", "#FEBA4D", "#FDA71A", "#FD9D00", "#CA7E00", "#985E00", "#653F00", "#331F00"],
              ["#FAF5EA", "#EFE0C0", "#E4CC96", "#D9B86C", "#CEA342", "#C9992D", "#A17A24", "#795C1B", "#503D12", "#281F09"],
              ["#ECF2EC", "#C5D8C7", "#9FBFA2", "#79A57C", "#528B57", "#3F7E44", "#326536", "#264C29", "#19321B", "#0D190E"],
              ["#E7F5FB", "#B6E0F4", "#85CBEC", "#54B6E4", "#23A1DD", "#0A97D9", "#0879AE", "#065B82", "#043C57", "#021E2B"],
              ["#EEF9EA", "#CCECBF", "#ABE095", "#89D36B", "#67C640", "#56C02B", "#459A22", "#34731A", "#224D11", "#112609"],
              ["#E6F0F5", "#B3D2E2", "#80B4CE", "#4D95BA", "#1A77A7", "#00689D", "#00537E", "#003E5E", "#002A3F", "#00151F"],
              ["#E8EDF0", "#BAC8D2", "#8CA4B5", "#5E7F97", "#305A79", "#19486A", "#143A55", "#0F2B40", "#0A1D2A", "#050E15"]]
  # --- stop ---

  # Set the color for boundaries that have no data.
  noValueColor: 'rgba(255,255,255,0.2)'
  # For documentation on the style options below, see here:
  # https://leafletjs.com/reference-1.4.0.html#path-option
  # Set the default style for boundaries in the map:
  styleNormal:
    weight: 1
    opacity: 1
    color: '#888'
    fillOpacity: 0.7
  # Set the style for boundaries that have been selected/highlighted:
  styleHighlighted:
    weight: 1
    opacity: 1
    color: '#111'
    fillOpacity: 0.7
  # Set the style for top-level boundaries that are displaying in other layers.
  # Note: This is only applicable when using the "nested zoom" feature (see below).
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: 5,5

map_layers:
  - serviceUrl:  https://Nachhaltige-Entwicklung-Deutschland.github.io/open-sdg-site-starter/assets/maps/boundaries.geojson
    min_zoom: 4.5
    max_zoom: 6.5
    staticBorders: true
    subfolder: laender
    label: indicator.laender
  - serviceUrl:  https://Nachhaltige-Entwicklung-Deutschland.github.io/open-sdg-site-starter/assets/maps/boundariesKrs.geojson
    min_zoom: 7
    max_zoom: 11
    staticBorders: false
    subfolder: kreise
    label: indicator.counties
    
progressive_web_app:
  enabled: true
  name: DNS Indikatoren
  short_name: DNS App
  precaching: true
